name: CI Testing
on:
  schedule:
   - cron: '*/15 * * * *'
  push:
    branches:
      - "*"
  pull_request:
    types: ['opened']
jobs:
  lint-api: 
    name: 'Lint API tests folder'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: latest
      - name: check node
        run: node -v
      - name: Install dependecies
        working-directory: ./lesson-14
        run: npm i
      - name: Run lint
        working-directory: ./lesson-14
        run: npm run lint
  lint-cypress: 
    name: 'Lint Cypress tests folder'
    runs-on: ubuntu-latest
    container:
      image: node:25-slim 
    steps:
      - uses: actions/checkout@v6
      - name: check node
        run: node -v
      - name: Install dependecies
        working-directory: ./cypress-project
        run: npm i
      - name: Run lint
        working-directory: ./cypress-project
        run: npm run lint
  lint-pw: 
    name: 'Lint PW tests folder'
    runs-on: ubuntu-latest
    container:
      image: node:25-slim 
    steps:
      - uses: actions/checkout@v7
      - name: check node
        run: node -v
      - name: Install dependecies
        working-directory: ./playwright-project
        run: npm i
      - name: Run lint
        working-directory: ./playwright-project
        run: npm run lint
  test-api: 
    name: 'API tests Jest'
    if: ${{ always() }}
    needs: lint-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: latest
      - name: Install dependecies
        working-directory: ./lesson-14
        run: npm i
      - name: Run api test
        working-directory: ./lesson-14
        run: npm run test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-api-html-report
          path: |
                lesson-14/html-report/
          retention-days: 3
  test-cypress: 
    name: 'Cypress e2e tests'
    needs: lint-cypress
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers: [1, 2, 3]
        # NODE_INDEX: [1, 2, 3]
        # NODE_TOTAL: [3]
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.EXAMPLE_RECORDING_KEY }}
      NODE_INDEX: ${{ matrix.containers }}
      # NODE_INDEX: ${{ matrix.NODE_INDEX }}
      # NODE_TOTAL: ${{ matrix.NODE_TOTAL }}
      SOME_VAR_NAME: ${{ secrets.SOME_VAR_NAME }}
      SOME_VISIBLE_VAR: ${{ vars.SOME_VISIBLE_VAR }}
    container:
     image: cypress/included:latest
     options: --user 1001
    steps:
      - uses: actions/checkout@v7
      - name: Install dependencies
        working-directory: ./cypress-project
        run: npm ci
      - uses: cypress-io/github-action@v7
        with:
          browser: chrome
          parallel: true
          group: 'Cypress e2e tests'
          record: true
          working-directory: ./cypress-project
      # - name: Run cypress tests in parallel
      #   working-directory: ./cypress-project
      #   run: npm run cypress:parallel:ci
      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: cypress-report-default-${{ matrix.containers }}
          path: |
                cypress-project/cypress/reports/
          retention-days: 3
  tests-playwright: 
    name: 'PW e2e tests'
    needs: lint-pw
    runs-on: ubuntu-latest
    container:
     image: mcr.microsoft.com/playwright:v1.62.0
    env:
        TESTOMATIO: ${{ secrets.TESTOMATIO }}
        TESTOMATIO_CREATE: ${{ vars.TESTOMATIO_CREATE }}
    steps:
      - uses: actions/checkout@v7
      - name: Install dependencies
        working-directory: ./playwright-project
        run: |
              npm ci
              npx playwright install chrome
      - name: Run e2e tests
        working-directory: ./playwright-project
        run: |
              npm run playwright:test:headless:chrome:qa1
      - uses: actions/upload-artifact@v7
        if: ${{ failure() || success() }}
        with:
          name: playwright-report
          path: |
                playwright-project/playwright-report/
                playwright-project/test-results/
          retention-days: 3
      - uses: actions/download-artifact@v7
        if: ${{ failure() || success() }}
        with:
          name: playwright-report
          path: |
                playwright-project/playwright-report/
                playwright-project/test-results/
          retention-days: 3